/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realty;

import com.mysql.jdbc.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Вадим
 */
public class AddRealty extends javax.swing.JFrame {

    /**
     * Creates new form AddRealty
     */
    public AddRealty() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextStreet = new javax.swing.JTextField();
        jTextHouse = new javax.swing.JTextField();
        jTextFlat = new javax.swing.JTextField();
        jTextArea = new javax.swing.JTextField();
        jTextFloor = new javax.swing.JTextField();
        jTextNum_room = new javax.swing.JTextField();
        jTextPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBoxFH = new javax.swing.JComboBox();

        jLabel8.setText("jLabel8");

        jLabel1.setText("Вулиця");

        jLabel2.setText("№ будинку");

        jLabel3.setText("№ квартири");

        jLabel4.setText("Площа(м2)");

        jLabel5.setText("Поверх");

        jLabel6.setText("К-ть кімнат");

        jLabel7.setText("Ціна");

        jLabel9.setText("Будинок чи квартира");

        jTextHouse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextHouseKeyPressed(evt);
            }
        });

        jButton1.setText("Ввести");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxFH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Будинок", "Квартира" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFlat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFloor)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextNum_room))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFH, 0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNum_room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkString(String string) {
        try {
            Integer.valueOf(string);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(!checkString(jTextArea.getText())){
           JOptionPane.showMessageDialog(null, "Площу не вірно введено!");
           return;
       }
       if((jTextArea.getText().length()>10)||(jTextArea.getText().length()<1))
       {
           JOptionPane.showMessageDialog(null, "Площу не вірно введено!");
           return;
       }
       if(!checkString(jTextFlat.getText())){
           JOptionPane.showMessageDialog(null, "Квартира не вірно введена!");
           return;
       }
       if((jTextFlat.getText().length()>6)||(jTextFlat.getText().length()<1))
       {
           JOptionPane.showMessageDialog(null, "Квартира не вірно введена!");
           return;
       }
       if(!checkString(jTextFloor.getText())){
           JOptionPane.showMessageDialog(null, "Поверх введений не вірно!");
           return;
       }
       if((jTextFloor.getText().length()>4)||(jTextFloor.getText().length()<1))
       {
           JOptionPane.showMessageDialog(null, "Поверх введений не вірно!");
           return;
       }
       
       if(!checkString(jTextHouse.getText())){
           JOptionPane.showMessageDialog(null, "Номер дому введений не вірно!");
           return;
       }
       if((jTextHouse.getText().length()>6)||(jTextFloor.getText().length()<1))
       {
           JOptionPane.showMessageDialog(null, "Номер дому введений не вірно!");
           return;
       }
       
       if(!checkString(jTextNum_room.getText())){
           JOptionPane.showMessageDialog(null, "Кількість кімнат не вірно введено!");
           return;
       }
       if((jTextNum_room.getText().length()>3)||(jTextNum_room.getText().length()<1))
       {
           JOptionPane.showMessageDialog(null, "Кількість кімнат не вірно введено!");
           return;
       }
       
       if(!checkString(jTextPrice.getText())){
           JOptionPane.showMessageDialog(null, "Ціна введена не вірно!");
           return;
       }
       if((jTextPrice.getText().length()>12)||(jTextPrice.getText().length()<1))
       {
           JOptionPane.showMessageDialog(null, "Ціна введена не вірно!");
           return;
       }
        
        if((jTextStreet.getText().length()>255)||(jTextStreet.getText().length()==0))
       {
           JOptionPane.showMessageDialog(null, "Вулиця введена невірно!");
           return;
       }
       java.sql.Connection con = null;
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root","");
        }catch(Exception e){
            System.out.println("No Connecntion");
        }
        java.sql.Statement stmt = null;
        String query;

        int fh;      
        if(jComboBoxFH.getComponentCount()==1)
            fh = 1;
        else
            fh = 2;
        try{
            stmt = con.createStatement();
            query = "INSERT INTO realty.realty(street, house, flat, area, floor, room_numb, priсe, fh) VALUES('"+
                    jTextStreet.getText()+"',"+jTextHouse.getText()+","+jTextFlat.getText()+","+jTextArea.getText()+
                    ","+jTextFloor.getText()+","+jTextNum_room.getText()+","+jTextPrice.getText()
                            +","+fh+")";
            stmt.executeUpdate(query);
            
            
            
        }catch(Exception ex){
            System.out.println("Erro "+ex);
        }finally{
            if(stmt != null) {try {
                stmt.close();
                jTextStreet.setText("");
                jTextHouse.setText("");
                jTextFlat.setText("");
                jTextArea.setText("");
                jTextFloor.setText("");
                jTextNum_room.setText("");
                jTextPrice.setText("");
                } catch (SQLException ex) {
                    Logger.getLogger(AddRealty.class.getName()).log(Level.SEVERE, null, ex);
                }
}
        }
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextHouseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextHouseKeyPressed

    }//GEN-LAST:event_jTextHouseKeyPressed

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddRealty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddRealty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddRealty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddRealty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddRealty().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxFH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextArea;
    private javax.swing.JTextField jTextFlat;
    private javax.swing.JTextField jTextFloor;
    private javax.swing.JTextField jTextHouse;
    private javax.swing.JTextField jTextNum_room;
    private javax.swing.JTextField jTextPrice;
    private javax.swing.JTextField jTextStreet;
    // End of variables declaration//GEN-END:variables
}
